/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author Norberto
 */
public class ViewCompras extends javax.swing.JPanel {

    /**
     * Creates new form ViewCompras
     */
    public ViewCompras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jl_id_compras = new javax.swing.JLabel();
        jtf_id_compras = new javax.swing.JTextField();
        jl_id_empleado = new javax.swing.JLabel();
        jtf_id_empleado = new javax.swing.JTextField();
        jl_id_proveedor = new javax.swing.JLabel();
        jtf_id_proveedor = new javax.swing.JTextField();
        jl_fecha_compra = new javax.swing.JLabel();
        jtf_fecha_compra = new javax.swing.JTextField();
        jl_subtotal = new javax.swing.JLabel();
        jtf_subtotal = new javax.swing.JTextField();
        jl_iva = new javax.swing.JLabel();
        jtf_iva = new javax.swing.JTextField();
        jl_total = new javax.swing.JLabel();
        jtf_total = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 51, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Compras");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(511, 511, 511)
                .addComponent(jLabel1)
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 51, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jl_id_compras.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jl_id_compras.setText("Id_compras");

        jl_id_empleado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jl_id_empleado.setText("Id_empleado");

        jl_id_proveedor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jl_id_proveedor.setText("Id_proveedor");

        jl_fecha_compra.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jl_fecha_compra.setText("Fecha_compra");

        jl_subtotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jl_subtotal.setText("Subtotal");

        jl_iva.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jl_iva.setText("Iva");

        jl_total.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jl_total.setText("Total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(387, 387, 387)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_id_compras)
                    .addComponent(jl_id_empleado)
                    .addComponent(jl_id_proveedor)
                    .addComponent(jl_fecha_compra)
                    .addComponent(jl_subtotal)
                    .addComponent(jl_iva)
                    .addComponent(jl_total))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtf_id_compras)
                    .addComponent(jtf_id_empleado)
                    .addComponent(jtf_id_proveedor)
                    .addComponent(jtf_fecha_compra)
                    .addComponent(jtf_subtotal)
                    .addComponent(jtf_iva)
                    .addComponent(jtf_total, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtf_id_compras, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_id_compras))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_id_empleado)
                    .addComponent(jtf_id_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_id_proveedor)
                    .addComponent(jtf_id_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_fecha_compra)
                    .addComponent(jtf_fecha_compra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_subtotal)
                    .addComponent(jtf_subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_iva)
                    .addComponent(jtf_iva, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_total, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jl_total))
                .addGap(66, 66, 66)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jl_fecha_compra;
    private javax.swing.JLabel jl_id_compras;
    private javax.swing.JLabel jl_id_empleado;
    private javax.swing.JLabel jl_id_proveedor;
    private javax.swing.JLabel jl_iva;
    private javax.swing.JLabel jl_subtotal;
    private javax.swing.JLabel jl_total;
    private javax.swing.JTextField jtf_fecha_compra;
    private javax.swing.JTextField jtf_id_compras;
    private javax.swing.JTextField jtf_id_empleado;
    private javax.swing.JTextField jtf_id_proveedor;
    private javax.swing.JTextField jtf_iva;
    private javax.swing.JTextField jtf_subtotal;
    private javax.swing.JTextField jtf_total;
    // End of variables declaration//GEN-END:variables
}
