/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author Norberto
 */
public class ViewProductos extends javax.swing.JPanel {

    /**
     * Creates new form jpAlmacen
     */
    public ViewProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jl_id_producto = new javax.swing.JLabel();
        jtf_id_producto = new javax.swing.JTextField();
        jl_nombre_producto = new javax.swing.JLabel();
        jtf_nombre_producto = new javax.swing.JTextField();
        jl_tipo_producto = new javax.swing.JLabel();
        jtf_tipo_producto = new javax.swing.JTextField();
        jl_marca = new javax.swing.JLabel();
        jtf_marca = new javax.swing.JTextField();
        jl_precio_venta = new javax.swing.JLabel();
        jtf_precio_venta = new javax.swing.JTextField();
        jl_sku = new javax.swing.JLabel();
        jtf_sku = new javax.swing.JTextField();
        jl_lote = new javax.swing.JLabel();
        jtf_lote = new javax.swing.JTextField();
        jl_descripcion = new javax.swing.JLabel();
        jtf_descripcion = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1200, 600));

        jPanel1.setBackground(new java.awt.Color(255, 51, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Productos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(541, 541, 541)
                .addComponent(jLabel1)
                .addContainerGap(401, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 51, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jl_id_producto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jl_id_producto.setText("Id_producto");

        jl_nombre_producto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jl_nombre_producto.setText("Nombre_producto");

        jl_tipo_producto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jl_tipo_producto.setText("Tipo_producto");

        jl_marca.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jl_marca.setText("Marca");

        jl_precio_venta.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jl_precio_venta.setText("Precio_venta");

        jl_sku.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jl_sku.setText("Sku");

        jl_lote.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jl_lote.setText("Lote");

        jl_descripcion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jl_descripcion.setText("Descripción");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_id_producto)
                    .addComponent(jl_nombre_producto)
                    .addComponent(jl_tipo_producto)
                    .addComponent(jl_marca))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtf_id_producto)
                    .addComponent(jtf_nombre_producto)
                    .addComponent(jtf_tipo_producto)
                    .addComponent(jtf_marca, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_precio_venta)
                    .addComponent(jl_sku)
                    .addComponent(jl_lote)
                    .addComponent(jl_descripcion))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtf_precio_venta)
                    .addComponent(jtf_sku)
                    .addComponent(jtf_lote)
                    .addComponent(jtf_descripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_id_producto)
                    .addComponent(jtf_id_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_precio_venta)
                    .addComponent(jtf_precio_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jl_nombre_producto)
                    .addComponent(jtf_nombre_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_sku)
                    .addComponent(jtf_sku))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_tipo_producto)
                    .addComponent(jtf_tipo_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_lote)
                    .addComponent(jtf_lote, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jl_marca)
                    .addComponent(jtf_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_descripcion)
                    .addComponent(jtf_descripcion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jl_descripcion;
    private javax.swing.JLabel jl_id_producto;
    private javax.swing.JLabel jl_lote;
    private javax.swing.JLabel jl_marca;
    private javax.swing.JLabel jl_nombre_producto;
    private javax.swing.JLabel jl_precio_venta;
    private javax.swing.JLabel jl_sku;
    private javax.swing.JLabel jl_tipo_producto;
    private javax.swing.JTextField jtf_descripcion;
    private javax.swing.JTextField jtf_id_producto;
    private javax.swing.JTextField jtf_lote;
    private javax.swing.JTextField jtf_marca;
    private javax.swing.JTextField jtf_nombre_producto;
    private javax.swing.JTextField jtf_precio_venta;
    private javax.swing.JTextField jtf_sku;
    private javax.swing.JTextField jtf_tipo_producto;
    // End of variables declaration//GEN-END:variables
}
