/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author Dany
 */
public class ViewEmpleados extends javax.swing.JPanel {

    /**
     * Creates new form ViewEmpleados
     */
    public ViewEmpleados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel2 = new javax.swing.JPanel();
        jPanelAdminDeUSers1 = new javax.swing.JPanel();
        jLabelAdmUsuLogo1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanelAdminDeUSers2 = new javax.swing.JPanel();
        jp_datospersonales = new javax.swing.JPanel();
        jl_id_empleado = new javax.swing.JLabel();
        jtf_id_empleado = new javax.swing.JTextField();
        jl_nombre_empleado = new javax.swing.JLabel();
        jtf_nombre_empleado = new javax.swing.JTextField();
        jl_apellido_paterno = new javax.swing.JLabel();
        jtf_apellido_paterno_empleado = new javax.swing.JTextField();
        jl_apellido_materno = new javax.swing.JLabel();
        jtf_apellido_materno_empleado = new javax.swing.JTextField();
        jl_telefono = new javax.swing.JLabel();
        jtf_telefono_empleado = new javax.swing.JTextField();
        jl_rfc = new javax.swing.JLabel();
        jtf_rfc_empleado = new javax.swing.JTextField();
        jl_calle = new javax.swing.JLabel();
        jtf_calle_empleado = new javax.swing.JTextField();
        jl_colonia = new javax.swing.JLabel();
        jtf_colonia_empleado = new javax.swing.JTextField();
        jl_numero_interior = new javax.swing.JLabel();
        jtf_numero_exterior_empleado = new javax.swing.JTextField();
        jl_numero_exterior = new javax.swing.JLabel();
        jtf_codigo_postal_empleado = new javax.swing.JTextField();
        jl_codigo_postal = new javax.swing.JLabel();
        jtf_no_interior_empleado = new javax.swing.JTextField();
        jl_no_cueta = new javax.swing.JLabel();
        jtf_no_cueta_empleado = new javax.swing.JTextField();
        jl_no_seguro = new javax.swing.JLabel();
        jtf_no_seguro_empleado = new javax.swing.JTextField();
        jl_banco = new javax.swing.JLabel();
        jtf_banco_empleado = new javax.swing.JTextField();
        jl_curp = new javax.swing.JLabel();
        jtf_curp = new javax.swing.JTextField();
        jl_tipo_empleado = new javax.swing.JLabel();
        jtf_tipo_empleado = new javax.swing.JTextField();
        jl_usuario = new javax.swing.JLabel();
        jtf_usuario_empleado = new javax.swing.JTextField();
        jl_contrasena = new javax.swing.JLabel();
        jtf_contrasena = new javax.swing.JTextField();
        jb_eliminar = new javax.swing.JButton();
        jb_insertar = new javax.swing.JButton();
        jb_modificar = new javax.swing.JButton();
        jb_cancelar = new javax.swing.JButton();
        jb_nuevo = new javax.swing.JButton();
        jl_codigo_postal1 = new javax.swing.JLabel();
        jtf_sucursal_empleado = new javax.swing.JTextField();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_Empleados = new javax.swing.JTable();

        jPanel2.setBackground(new java.awt.Color(204, 51, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(452, 60));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanelAdminDeUSers1.setBackground(new java.awt.Color(204, 51, 0));
        jPanelAdminDeUSers1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelAdminDeUSers1.setPreferredSize(new java.awt.Dimension(425, 60));

        jLabel6.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Administración de Empleados");

        javax.swing.GroupLayout jPanelAdminDeUSers1Layout = new javax.swing.GroupLayout(jPanelAdminDeUSers1);
        jPanelAdminDeUSers1.setLayout(jPanelAdminDeUSers1Layout);
        jPanelAdminDeUSers1Layout.setHorizontalGroup(
            jPanelAdminDeUSers1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdminDeUSers1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAdmUsuLogo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAdminDeUSers1Layout.setVerticalGroup(
            jPanelAdminDeUSers1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdminDeUSers1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAdminDeUSers1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAdminDeUSers1Layout.createSequentialGroup()
                        .addComponent(jLabelAdmUsuLogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanelAdminDeUSers2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelAdminDeUSers2.setOpaque(false);

        jp_datospersonales.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Personales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jp_datospersonales.setOpaque(false);

        jl_id_empleado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_id_empleado.setText("ID Empleado");

        jtf_id_empleado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jl_nombre_empleado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_nombre_empleado.setText("Nombre (s)");

        jtf_nombre_empleado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jl_apellido_paterno.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_apellido_paterno.setText("Apellido Paterno");

        jtf_apellido_paterno_empleado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jl_apellido_materno.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_apellido_materno.setText("Apellido Materno");

        jtf_apellido_materno_empleado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jl_telefono.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_telefono.setText("Teléfono");

        jtf_telefono_empleado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jtf_telefono_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_telefono_empleadoActionPerformed(evt);
            }
        });

        jl_rfc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_rfc.setText("R.F.C");

        jtf_rfc_empleado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jl_calle.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_calle.setText("Calle");

        jtf_calle_empleado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jl_colonia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_colonia.setText("Colonia");

        jtf_colonia_empleado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jl_numero_interior.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_numero_interior.setText("Número exterior");

        jtf_numero_exterior_empleado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jl_numero_exterior.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_numero_exterior.setText("Número exterior");

        jtf_codigo_postal_empleado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jl_codigo_postal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_codigo_postal.setText("Código postal");

        jtf_no_interior_empleado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jl_no_cueta.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_no_cueta.setText("No. Cuenta");

        jtf_no_cueta_empleado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jtf_no_cueta_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_no_cueta_empleadoActionPerformed(evt);
            }
        });

        jl_no_seguro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_no_seguro.setText("No. Seguro");

        jtf_no_seguro_empleado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jl_banco.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_banco.setText("Banco");

        jtf_banco_empleado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jl_curp.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_curp.setText("Curp");

        jtf_curp.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jl_tipo_empleado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_tipo_empleado.setText("Tipo empleado");

        jtf_tipo_empleado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jl_usuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_usuario.setText("Usuario");

        jtf_usuario_empleado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jl_contrasena.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_contrasena.setText("Contraseña");

        jtf_contrasena.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jb_eliminar.setText("Eliminar");

        jb_insertar.setText("Insertar");

        jb_modificar.setText("Modificar");

        jb_cancelar.setText("Cancelar");

        jb_nuevo.setText("Nuevo");

        jl_codigo_postal1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_codigo_postal1.setText("Sucursal");

        jtf_sucursal_empleado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        javax.swing.GroupLayout jp_datospersonalesLayout = new javax.swing.GroupLayout(jp_datospersonales);
        jp_datospersonales.setLayout(jp_datospersonalesLayout);
        jp_datospersonalesLayout.setHorizontalGroup(
            jp_datospersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_datospersonalesLayout.createSequentialGroup()
                .addGroup(jp_datospersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jp_datospersonalesLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jp_datospersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_nombre_empleado)
                            .addComponent(jl_id_empleado)
                            .addComponent(jl_apellido_paterno)
                            .addComponent(jl_apellido_materno)
                            .addComponent(jl_telefono)
                            .addComponent(jl_calle)
                            .addComponent(jl_colonia)
                            .addComponent(jl_numero_interior)
                            .addComponent(jl_numero_exterior))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addGroup(jp_datospersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_id_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jp_datospersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jtf_no_interior_empleado, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtf_numero_exterior_empleado, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtf_colonia_empleado, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtf_calle_empleado, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtf_telefono_empleado, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtf_apellido_materno_empleado, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtf_apellido_paterno_empleado, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtf_nombre_empleado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))))
                    .addGroup(jp_datospersonalesLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_nuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jb_insertar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jb_cancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jb_modificar)
                        .addGap(13, 13, 13)
                        .addComponent(jb_eliminar)
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 255, Short.MAX_VALUE)
                .addGroup(jp_datospersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_datospersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jp_datospersonalesLayout.createSequentialGroup()
                            .addComponent(jl_no_cueta, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                            .addComponent(jtf_no_cueta_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jp_datospersonalesLayout.createSequentialGroup()
                            .addGroup(jp_datospersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jp_datospersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jl_no_seguro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jl_tipo_empleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jl_usuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jl_contrasena, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jl_curp, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jp_datospersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_datospersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtf_curp, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_tipo_empleado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jp_datospersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jtf_contrasena)
                                        .addComponent(jtf_usuario_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jtf_codigo_postal_empleado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_datospersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtf_banco_empleado)
                                    .addComponent(jtf_no_seguro_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(jl_banco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jl_rfc, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_codigo_postal)
                    .addComponent(jl_codigo_postal1)
                    .addGroup(jp_datospersonalesLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addGroup(jp_datospersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_rfc_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_sucursal_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(70, 70, 70))
        );
        jp_datospersonalesLayout.setVerticalGroup(
            jp_datospersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_datospersonalesLayout.createSequentialGroup()
                .addGroup(jp_datospersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_datospersonalesLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jp_datospersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jp_datospersonalesLayout.createSequentialGroup()
                                .addGroup(jp_datospersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtf_apellido_materno_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jl_apellido_materno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(jp_datospersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtf_telefono_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jl_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(jp_datospersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtf_calle_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jl_calle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(jp_datospersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jp_datospersonalesLayout.createSequentialGroup()
                                        .addComponent(jtf_colonia_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(jtf_numero_exterior_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jp_datospersonalesLayout.createSequentialGroup()
                                        .addComponent(jl_colonia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(jl_numero_interior, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jp_datospersonalesLayout.createSequentialGroup()
                                .addGroup(jp_datospersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jp_datospersonalesLayout.createSequentialGroup()
                                        .addComponent(jtf_no_cueta_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(45, 45, 45))
                                    .addGroup(jp_datospersonalesLayout.createSequentialGroup()
                                        .addComponent(jl_no_cueta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addGroup(jp_datospersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jtf_no_seguro_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jl_no_seguro, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(20, 20, 20)
                                .addGroup(jp_datospersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtf_banco_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jl_banco, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jp_datospersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jl_curp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_curp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(jp_datospersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jl_tipo_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_tipo_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(jp_datospersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtf_usuario_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jl_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(jp_datospersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jl_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(20, 20, 20)
                        .addGroup(jp_datospersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_no_interior_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_codigo_postal_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jp_datospersonalesLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jp_datospersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jl_numero_exterior, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jl_codigo_postal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jp_datospersonalesLayout.createSequentialGroup()
                        .addGroup(jp_datospersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_id_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_id_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_rfc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_rfc_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jp_datospersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtf_nombre_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_nombre_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jp_datospersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtf_apellido_paterno_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_apellido_paterno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_datospersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jp_datospersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jb_nuevo)
                        .addComponent(jb_cancelar)
                        .addComponent(jb_modificar)
                        .addComponent(jb_insertar)
                        .addComponent(jb_eliminar))
                    .addGroup(jp_datospersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtf_sucursal_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jp_datospersonalesLayout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(jl_codigo_postal1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelAdminDeUSers2Layout = new javax.swing.GroupLayout(jPanelAdminDeUSers2);
        jPanelAdminDeUSers2.setLayout(jPanelAdminDeUSers2Layout);
        jPanelAdminDeUSers2Layout.setHorizontalGroup(
            jPanelAdminDeUSers2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdminDeUSers2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp_datospersonales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelAdminDeUSers2Layout.setVerticalGroup(
            jPanelAdminDeUSers2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdminDeUSers2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jp_datospersonales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLayeredPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanelAdminDeUSers1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanelAdminDeUSers2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelAdminDeUSers1, javax.swing.GroupLayout.DEFAULT_SIZE, 1372, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1372, Short.MAX_VALUE)
                    .addComponent(jPanelAdminDeUSers2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelAdminDeUSers1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAdminDeUSers2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Empleados", jLayeredPane1);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista"));
        jPanel1.setOpaque(false);

        jt_Empleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jt_Empleados);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1336, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLayeredPane2.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Empleados", jLayeredPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_telefono_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_telefono_empleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_telefono_empleadoActionPerformed

    private void jtf_no_cueta_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_no_cueta_empleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_no_cueta_empleadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelAdmUsuLogo1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelAdminDeUSers1;
    private javax.swing.JPanel jPanelAdminDeUSers2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JButton jb_cancelar;
    public javax.swing.JButton jb_eliminar;
    public javax.swing.JButton jb_insertar;
    public javax.swing.JButton jb_modificar;
    public javax.swing.JButton jb_nuevo;
    public javax.swing.JLabel jl_apellido_materno;
    public javax.swing.JLabel jl_apellido_paterno;
    public javax.swing.JLabel jl_banco;
    public javax.swing.JLabel jl_calle;
    public javax.swing.JLabel jl_codigo_postal;
    public javax.swing.JLabel jl_codigo_postal1;
    public javax.swing.JLabel jl_colonia;
    public javax.swing.JLabel jl_contrasena;
    public javax.swing.JLabel jl_curp;
    public javax.swing.JLabel jl_id_empleado;
    public javax.swing.JLabel jl_no_cueta;
    public javax.swing.JLabel jl_no_seguro;
    public javax.swing.JLabel jl_nombre_empleado;
    public javax.swing.JLabel jl_numero_exterior;
    public javax.swing.JLabel jl_numero_interior;
    public javax.swing.JLabel jl_rfc;
    public javax.swing.JLabel jl_telefono;
    public javax.swing.JLabel jl_tipo_empleado;
    public javax.swing.JLabel jl_usuario;
    private javax.swing.JPanel jp_datospersonales;
    public javax.swing.JTable jt_Empleados;
    public javax.swing.JTextField jtf_apellido_materno_empleado;
    public javax.swing.JTextField jtf_apellido_paterno_empleado;
    public javax.swing.JTextField jtf_banco_empleado;
    public javax.swing.JTextField jtf_calle_empleado;
    public javax.swing.JTextField jtf_codigo_postal_empleado;
    public javax.swing.JTextField jtf_colonia_empleado;
    public javax.swing.JTextField jtf_contrasena;
    public javax.swing.JTextField jtf_curp;
    public javax.swing.JTextField jtf_id_empleado;
    public javax.swing.JTextField jtf_no_cueta_empleado;
    public javax.swing.JTextField jtf_no_interior_empleado;
    public javax.swing.JTextField jtf_no_seguro_empleado;
    public javax.swing.JTextField jtf_nombre_empleado;
    public javax.swing.JTextField jtf_numero_exterior_empleado;
    public javax.swing.JTextField jtf_rfc_empleado;
    public javax.swing.JTextField jtf_sucursal_empleado;
    public javax.swing.JTextField jtf_telefono_empleado;
    public javax.swing.JTextField jtf_tipo_empleado;
    public javax.swing.JTextField jtf_usuario_empleado;
    // End of variables declaration//GEN-END:variables
}
